### ISSUE TITLE
Issue running extended Hugo 0.43

### ISSUE THREAD

**Issue by LorenzCK** [klakegg/docker-hugo#1]
Hi,
I am currently unable to run any of the images with the new "extended" Hugo 0.43. It appears to be similar to an [issue of the jojomi/hugo image](https://github.com/jojomi/docker-hugo/issues/46), also based on Alpine.

```bash
docker run -it --rm klakegg/hugo:0.43-ext-alpine
```

always fails with

```
/run.sh: line 67: hugo: not found
```

**Comment by klakegg** [comment]
Thank you for providing feedback.

I just discovered this myself while setting up configuration for Travis.

I've been looking into this, and it looks to me like this is related to the compilation process of Hugo. I've posted gohugoio/hugo#4939 to hopefully get this fixed in 0.43.1.

**Comment by klakegg** [comment]
Using Alpine and Busybox with glibc does not seem to be enough, so I've simply added images using Debian and Ubuntu as base image.

I'll have to look into what to do about Busybox and Alpine regarding extended edition, and I may add a Asciidoctor image with Debian/Ubuntu as base image for extended edition a bit later.

I hope this solves your problem for now. New images are available at Docker Hub, and documentation is updated.

**Comment by klakegg** [comment]
I've been able to come up with a workaround for Alpine (and Asciidoctor) images to enable extended edition. Information about extended edition for Alpine is not yet documented.

@LorenzCK Could you verify the updated `klakegg/hugo:0.43-ext-alpine`?

**Comment by LorenzCK** [comment]
Nice workaround! Works perfectly. Thanks a lot! 👍

**Comment by klakegg** [comment]
Finally were I able to fix a bug related to build, and updated images for 0.43 and 0.44 are now available.

I'd recommend using `0.44-ext-debian` if you want to use the new postcss functionality (requires Node) in Hugo (as of 0.43).

I'm closing this issue for now, however I will keep track of features in extended edition in a separate table in the Readme file.

Thanks to all for supporting me in making sure Hugo extended edition works with Docker. :)
