### ISSUE TITLE
PostCSS doesn't find Autoprefixer

### ISSUE THREAD

**Issue by Kreepounet** [klakegg/docker-hugo#10]
Hi,

Tested on ext-ubuntu 0.57.2. PostCSS doesn't find Autoprefixer. If I install it locally in the site root, it works.

**Comment by klakegg** [comment]
Thank you for your feedback.

Autoprefixer is installed using `npm install -g autoprefixer postcss-cli` in the ext-ubuntu image. Which command did you use to install autoprefixer?

**Comment by Kreepounet** [comment]
Sorry if it wasn't clear. If I don't install anything and try to rely on the global installs of the ext-ubuntu image, hugo finds postcss-cli, but postcss-cli doesn't find autoprefixer. If I install just autoprefixer in the /src folder along with my hugo website (with the command npm install autoprefixer), the global postcss-cli installed by the image finds the local autoprefixer that I installed manually.

**Comment by klakegg** [comment]
I found this thread on this issue:
https://discourse.gohugo.io/t/hugo-pipes-postcss-how-to-use-global-autoprefixer/15699/12

I've confirmed this to be the case, so I'll find a way to fix it in the images. :)

**Comment by Kreepounet** [comment]
Thanks for your fast answer :)

**Comment by klakegg** [comment]
By adding the NODE_PATH, I think I've fixed this issue. I were able to reproduce your issue using [docsy](https://github.com/google/docsy), and with a local build of all ext images were I able to verify the fix.

I've triggered new publishing of 0.57.2 on Docker hub, I expect updated images to available in ~15-20 minutes.

**Comment by Kreepounet** [comment]
Tested and approved ! Thanks.
