### ISSUE TITLE
Set timezone to busybox

### ISSUE THREAD

**Issue by panakour** [klakegg/docker-hugo#12]
Hello, is there any way to change the timezone to busybox image before build the hugo site.

I want this because in my theme I use the ` .Date.Local` related to https://discourse.gohugo.io/t/dateformat-force-a-specific-timezone/9860
https://discourse.gohugo.io/t/different-timezones/18830

**Comment by ryancastle** [comment]
Using the non-busybox images seems to work fine when setting environment variables.
