### ISSUE TITLE
`Error: unknown command "sh" for "hugo"`

### ISSUE THREAD

**Issue by jallbrit** [klakegg/docker-hugo#13]
I am using this container for GitLab Pages. No matter what I specify to be run as a script, whether it's `hugo` or `echo hello`, I am greeted with this error message:

```
Error: unknown command "sh" for "hugo"
Run 'hugo --help' for usage.
Error: unknown command "sh" for "hugo"
Run 'hugo --help' for usage.
```

Notice it happens twice, that is not a copying error. I am unable to determine what is causing this. If I use other containers available for hugo from Docker Hub, it is successful. That must mean this container is what's causing the problem.

The problem persists despite changing the image. For example, I have tried `alpine`, `latest`, and `debian` to no avail. Same problem each time. I am willing to post my `.gitlab-ci.yml` if it is wanted, but I wasn't sure if it was relevant.

**Comment by adrian5** [comment]
I ran into this too, I think it's an issue [specific to GitLab's CI pipeline](https://gitlab.com/gitlab-org/gitlab-runner/issues/1421#note_61174777) and not this Docker container.

Try this jallbrit:
```yaml
…
image:
  name: klakegg/hugo:ext-alpine
  entrypoint: ["/bin/sh", "-c"]    # possible fix
```

**Comment by s0l4r** [comment]
I can confirm that this fix works!

**Comment by klakegg** [comment]
This image uses entrypoint to simplify usage. You may [get access to an interactive shell](https://github.com/klakegg/docker-hugo#hugo-shell) or override the Docker entrypoint if that suits your use case better. 

I know other images doesn't set entrypoint, however I've made the choice to use entrypoint because I think it makes most sense in most use cases.

**Comment by jmcgeheeiv** [comment]
@jmbarbier, note that you are using a different image. Perhaps that is why you had a problem with `entrypoint: ["/bin/sh", "-c"]`.

I found that `entrypoint: ["/bin/sh", "-c"]` does work with image `klakegg/hugo:ext-alpine`.

**Comment by klakegg** [comment]
It seems like more people are stumbling into this issue than I expected.

For anyone coming by, I'd suggest to have a look at the `klakegg/hugo:...-ci` images as [described in the readme](https://github.com/klakegg/docker-hugo#using-ci-image-0770-or-newer) as those variants may make your configuration a bit easier.

**Comment by jmcgeheeiv** [comment]
I was wondering what the `-ci` images were for. I thought they for some exotic use case, but it turns out that that they might be for the dominant use case.
