### ISSUE TITLE
Is there any chance you could add an option for calling `hugo version` before build

### ISSUE THREAD

**Issue by jasikpark** [klakegg/docker-hugo#16]
I really appreciate your github action! This is great!
 (The gohugio/hugo Dockerfile was last updated in 2017 :/)
I'm using `ext-alpine` and `latest-ext` to build against the latest hugo with git included daily - but i'd like to figure out how to indicate which version of hugo i'm actually building against

**Comment by klakegg** [comment]
Thank you for reaching out with your feature request. As this feature would result in everyone using the Docker image to build their Hugo webpage having to make an extra call to Hugo to have extra stuff in the shell not giving most of them extra value, I think I'll have to turn it down for now.
