### ISSUE TITLE
How to set environemnt when using onbuild images? Currently I can't

### ISSUE THREAD

**Issue by ieugen** [klakegg/docker-hugo#17]
Hi,

We are building a website with onbuild. 

How can we have a multi-stage docker build and we can't set the the HUGO_ENV value to somethings else during the build phase. 

```
# Stage 1 - build the website
FROM klakegg/hugo:0.62.2-ext-debian-onbuild as website_build

# The environment changes what config files are used.
# See https://gohugo.io/getting-started/configuration/#configuration-directory
# and https://github.com/klakegg/docker-hugo#configuration

# <<<<< does not work ?! 
ENV HUGO_ENV production

# Stage 2 - build the actual image
FROM nginx:stable

# Copy actual website over the rest of the resources
# https://github.com/klakegg/docker-hugo#using-an-onbuild-image
COPY --from=website_build /onbuild /usr/share/nginx/html

RUN cat /usr/share/nginx/html/index.html - uses old configuration ?!
```

```
tree config 
config
├── beta
│   └── config.toml
├── _default
│   └── config.toml
└── production
    └── config.toml


```

Production config.toml
```
cat config/production/config.toml 
baseURL = "https://www.production.com"% 
```

AllI see is the URL for `default`, not the production URL.

I think that this could work if `HUGO_ENV` is initialized from `HUGO_ENV` ARG by default and we can suuply the HUGO_ENV build arg during image build.

**Comment by ieugen** [comment]
Something like this: https://stackoverflow.com/questions/31198835/can-we-pass-env-variables-through-cmd-line-while-building-a-docker-image-through

**Comment by klakegg** [comment]
It seems like you try to use an onbuild image when you shouldn't. Please use a different image and call hugo explicitly.
