### ISSUE TITLE
Multistage build usage issue?

### ISSUE THREAD

**Issue by alexfdezsauco** [klakegg/docker-hugo#19]
I'm trying to use this image in a multistage way.

So, the first lines of the docker files looks like this. 

    FROM klakegg/hugo:0.66.0 
    WORKDIR /src
    COPY src/. .
    RUN hugo
    RUN ls /target

but if I list the /target directory is empty.

If I enter into a container 

    docker run -it --entrypoint "/bin/sh"  %image_id%

and run hugo, I the files are generated. 

The idea is host the output in an ngix but build the site in a single dockerfile.  So, the next stages could look like this. 

    FROM /nginx
    WORKDIR /usr/share/nginx/html/
    COPY --from=0 /target .

But I can't copy nothing from the target directory. 

Any idea?

**Comment by just1689** [comment]
I have the same problem this side

**Comment by just1689** [comment]
I'm using this one and it's working nicely

https://github.com/jojomi/docker-hugo

**Comment by klakegg** [comment]
As of 0.68.0 is all instances of `VOLUME` removed from my Dockerfiles in this repository. I think this will solve this problem.

Please also see the ONBUILD information in the project README.

**Comment by alexfdezsauco** [comment]
Thanks, it works.
