### ISSUE TITLE
Hugo modules don't work - golang missing

### ISSUE THREAD

**Issue by amuraru** [klakegg/docker-hugo#20]
Running site generation using this image:
```
docker run --rm -v "`pwd`":/src -v "`pwd`/site-pages":/target klakegg/hugo:0.67.1-ext-alpine --source="/src/exampleSite" --destination="/target" --ignoreCache
```
I get
```
Error: we found a go.mod file in your project, but you need to install Go to use it
```
Can you please add `golang` installation in the base docker image?
thanks

**Comment by klakegg** [comment]
Thank you for bringing this to my attention.

I've made the necessary changes for the 0.68.0 release (currently building).

**Comment by amuraru** [comment]
thanks @klakegg !

**Comment by sumutcan** [comment]
Hi,
0.74.3-alpine image does not have go-lang preinstalled

**Comment by klakegg** [comment]
I know, it is supposed to be in those images named `ext` only. Please see the README for information of this project.

**Comment by sumutcan** [comment]
Oh, yeah I missed that thanks. The alpine-ext image still gave some error regarding GCC though. 
"relocation error libstdc++.so.6"

ubuntu image works fine.
