### ISSUE TITLE
Feature request: rsync

### ISSUE THREAD

**Issue by remohammadi** [klakegg/docker-hugo#21]
Is it possible to include rsync in one of the variants?

I'm trying to use the image to build a bitbucket repository, and then push the result into a server using rsync+ssh.

**Comment by klakegg** [comment]
This image is created to serve as the packaged Hugo and with the extended images to contain all the requirements to fully use the power of Hugo. However I try to make sure the responsibility of the image ends after building the website as publishing/distribution is a different step of the build pipeline.

I fully understand adding rsync requires just another megabyte, however I think I'll not include it as that opens for including other tools related to publishing/distribution or other steps of the pipeline. This is also the reason why I did not include HTMLProofer in this image, it is a [different image](https://hub.docker.com/r/klakegg/html-proofer/).

I'd suggest to have a look at make if you are looking for a lightweight (and powerful) tool to line up your build pipeline.
