### ISSUE TITLE
Create hugo-unprivileged image

### ISSUE THREAD

**Issue by jimangel** [klakegg/docker-hugo#24]
@klakegg do you have any interest in me contributing an unpriviledged Dockerfile?

Similar to: https://hub.docker.com/r/nginxinc/nginx-unprivileged

This is mainly to deal with corporate security and allow the hugo container to run in environments that prevent running as root. I am using your image for https://github.com/jimangel/GitDocs and 2 of the 3 images don't run as root.

Alternately, if you don't have interest in adding this build, would you be willing to share your build process (triggers) and I could fork / maintain? Thanks!

**Comment by klakegg** [comment]
I've been making a lot of small changes recently to make sure all images support running unpriviledged, and my [edge images](https://hub.docker.com/repository/docker/klakegg/hugo/tags?page=1&name=edge), pushed as part of CI, seem to be working fine when running unpriviledged by setting `--user`.

Any feedback, both as issues and pull requests, provided to make the images better is valuable to me. :smile:

**Comment by jimangel** [comment]
I will do some more testing, I thought I had some problems but I didn't get too deep into testing.

Is there a preferred user to have it run as? Or any UID should work?

Thanks for the fast response!

**Comment by klakegg** [comment]
Any UID should work, at least according to my plan.

Looking forward to receive further feedback.

**Comment by jimangel** [comment]
I had a chance to test it again, it's Kubernetes, but should be similar to running docker with --user. I get the following error from the container:

```
sh: /src/git-sync/config:: unknown operand
Error: Error copying static files: chtimes /target/: operation not permitted
Building sites … Total in 88 ms
```

When I let hugo run as default user (root), it has no problem using `/target/` and the nginx container has no problem (not privileged) reading it. It's important to note that target is a mounted emptyDir from Kubernetes.

Looking at the directory from the nginx container the permissions are:

```
ls -lah </target/ in nginx>
total 20K
drwxrwsrwx 5 root  nogroup 4.0K May 12 22:09 .
drwxr-xr-x 3 root  root    4.0K Apr 24 22:42 ..
drwxr-sr-x 2 65533 nogroup 4.0K May 12 22:09 admin
drwxr-sr-x 2 65533 nogroup 4.0K May 12 22:09 img
drwxr-sr-x 3 65533 nogroup 4.0K May 12 22:09 js
```

I'm testing with:
```
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 65533
          runAsGroup: 65534
```

Hugo runs ok with the exact above parameters without `runAsUser`.

From the above output it seems like some of the content is copied before Hugo fails. If you'd like to test on your own you can:

1) install [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) and run:

2) clone https://github.com/jimangel/GitDocs

2) edit the deployment to include `runAsUser` [here](https://github.com/jimangel/GitDocs/blob/master/examples/base/gitdocs-deployment.yaml#L47)

3) run:
    ```
    kubectl apply -f examples/base/nginx-configmap.yaml
    kubectl apply -f examples/base/gitdocs-deployment.yaml
   ```

**Comment by jimangel** [comment]
Output of `/target` running Hugo as root:

```
/src # ls -lah /target/
total 128K   
drwxrwsrwx   15 root     nobody      4.0K May 12 22:27 .
drwxr-xr-x    1 root     root        4.0K May 12 22:27 ..
-rw-r--r--    1 root     nobody     12.6K May 12 22:27 404.html
drwxr-sr-x    2 root     nobody      4.0K May 12 22:27 admin
drwxr-sr-x    3 root     nobody      4.0K May 12 22:27 author
drwxr-sr-x    3 root     nobody      4.0K May 12 22:27 authors
drwxr-sr-x    3 root     nobody      4.0K May 12 22:27 categories
drwxr-sr-x    2 root     nobody      4.0K May 12 22:27 css
drwxr-sr-x    2 root     nobody      4.0K May 12 22:27 images
drwxr-sr-x    2 root     nobody      4.0K May 12 22:27 img
-rw-r--r--    1 root     nobody     32.2K May 12 22:27 index.html
-rw-r--r--    1 root     nobody      1.3K May 12 22:27 index.json
-rw-r--r--    1 root     nobody       538 May 12 22:27 index.webmanifest
-rw-r--r--    1 root     nobody       611 May 12 22:27 index.xml
drwxr-sr-x    3 root     nobody      4.0K May 12 22:27 js
drwxr-sr-x    3 root     nobody      4.0K May 12 22:27 post
drwxr-sr-x    2 root     nobody      4.0K May 12 22:27 publication
drwxr-sr-x    3 root     nobody      4.0K May 12 22:27 publication_types
-rw-r--r--    1 root     nobody       594 May 12 22:27 sitemap.xml
drwxr-sr-x    3 root     nobody      4.0K May 12 22:27 tags
drwxr-sr-x    2 root     nobody      4.0K May 12 22:27 talk
```

**Comment by klakegg** [comment]
Did you use `klakegg/hugo:0.70.0-ext-alpine` or one of the edge images?

**Comment by jimangel** [comment]
I didn't use the edge versions, let me try that. Sorry.

In the event the edge ones work, do you have plans on cherry picking the changes to all releases?

**Comment by jimangel** [comment]
When I update to `klakegg/hugo:edge-ext-alpine` and change to `runAsUser: 65533` things break. At first it looked like an nginx error:

```
directory index of "/usr/share/nginx/html/" is forbidden
```

If I look at the hugo logs I see

```
```

But when I look in the hugo container, I see the target dir is empty

```
 kubectl exec -it $POD -c hugo -- /bin/sh
/src $ ls -lah /target/
total 8K     
drwxrwsrwx    2 root     nobody      4.0K May 20 23:23 .
drwxr-xr-x    1 root     root        4.0K May 20 23:23 ..
```

**Comment by klakegg** [comment]
I'm able to reproduce the error message, and I'm able to make it go away by changing `HUGO_DESTINATION` from `/target` to `../target` (given source in `/src`).

I'm not looking into changing previous releases as it is important to me to make sure existing configuration and pipelines using previous releases don't break because of future changes, so changes will be made available in future releases. We have a new release of Hugo quite often, so I guess that shouldn't be a problem.

**Comment by klakegg** [comment]
I think I may have found the reason for the error message:
https://github.com/gohugoio/hugo/issues/7302

**Comment by jimangel** [comment]
Good find! After some further testing, it seemed like it ran fine when hugo was the sole owner of the volume (or root). When I used nginx (even read only) it would error out.

I have subscribed to the issue you opened. Thanks!

**Comment by klakegg** [comment]
I've now pushed updated edge images containing the workaround. Could you verify this?

If you want to run an older version of Hugo, simply set the `HUGO_VERSION` environment variable to automatically download and bypass the included version.

**Comment by jimangel** [comment]
That works! Thanks for your attention to this and the tip on `HUGO_VERSION`!

**Comment by klakegg** [comment]
Thank you for creating this issue and helping me making better Docker images.

Images for Hugo `0.71.1` is now out, so you may change your configuration to reference a stable image. :smile:
