### ISSUE TITLE
docker tags with prefix 0.72.0 are not on docker.io

### ISSUE THREAD

**Issue by rparree** [klakegg/docker-hugo#26]
Hi,

Following the updated of hugo to 0.72.0 i wanted to updated my docker containers. However on docker hub there are only updated versions available without the 0.72.0 prefix (iow `edge-ext-alpine` but not `0.72.0-ext-alpine`)

Perhaps i am overlooking something?

**Comment by rparree** [comment]
I turns out `edge-ext-alpine` is still v0.71.1-A301F6B2/extended.

**Comment by klakegg** [comment]
All images for 0.72.0 are now available. Sorry for the inconvenience.

**Comment by rparree** [comment]
Great, thanks:)
