### ISSUE TITLE
Readme? Hugo Extended

### ISSUE THREAD

**Issue by damien1** [klakegg/docker-hugo#29]
Hi .. I need to use Hugo Extended ... however in the Readme i says Hugo 0.43
 
I assume that is a typo and should be v0.743 ??

https://github.com/klakegg/docker-hugo/blob/master/README.md#hugo-extended-edition

**Comment by klakegg** [comment]
The text above the table says:

> Table of Hugo extention features and the version when images first support the feature:

Why do you think it should be "v0.743"?
