### ISSUE TITLE
Using Private Hugo module in Gitlab during Docker image building

### ISSUE THREAD

**Issue by divyakumarjain** [klakegg/docker-hugo#31]
Trying to use Hugo modules (Go Module) from Privates repository. Seems like Hugo needs credentials to download the private Hugo module during build/serve which causes following step in Dockerfile fail.

```FROM klakegg/hugo:0.74.3-onbuild AS hugo```

May there should be a way to run below type of command before the hugo build starts

```
git config \
    --global \
    url."https://${bitbucket_id}:${bitbucket_token}@privatebitbucket.com/".insteadOf \
    "https://privatebitbucket.com/"
```
 Ref: https://medium.com/cloud-native-the-gathering/go-modules-with-private-git-repositories-dfe795068db4

**Comment by klakegg** [comment]
I'm performing mulitple commands during regular Hugo builds using the existing images. It is up to you to choose your tooling.
