### ISSUE TITLE
ARM-based docker images

### ISSUE THREAD

**Issue by oonid** [klakegg/docker-hugo#34]
Hi! Thank you for the very updated docker images for Hugo.

Is there any plan to produce ARM-based docker images?

**Comment by klakegg** [comment]
So, there is good and bad news regarding this.

First the bad news:
* Hugo extended edition is currently not available for other platforms than amd64.
* Pandoc is currently not available for other platforms than amd64.
* I build a lot of images for Hugo, and I'd prefer to make "the same" image for all architectures when enabling more architectures.

And to the good news:
* I'm working on the toolchain to make me able to build images for Hugo targeting multiple architectures.
* I hope to run Hugo on my Raspberry Pi 4 in 2020.

The current state is not optimal, however I expect this to change at some point. :)

**Comment by logoff** [comment]
It's a pity that pandoc and Hugo extended are not available outside amd64... Whenever you have news about ARM support, I'll be very please to test it. I want to use it in my Raspberry Pi's 😉

**Comment by alvarogg777** [comment]
Hugo extended for ARM64 MacOS has been released, and there are docs on how to build for linux arm64 and containers already built with SASS and pandoc yet not officially released @klakegg (see https://hub.docker.com/r/jakejarvis/hugo-extended)

**Comment by klakegg** [comment]
I've pushed some new [`edge` images](https://hub.docker.com/r/klakegg/hugo/tags?page=1&ordering=last_updated&name=edge) for Hugo standard edition with support for arm64 and arm/v7. I prefer to not build the software myself, however that may change.

The list of software not currently available:
- [ ] [Hugo](https://github.com/gohugoio/hugo) - extended edition (arm64)
- [ ] [Hugo](https://github.com/gohugoio/hugo) - extended edition (arm/v7)
- [ ] [Pandoc](https://github.com/jgm/pandoc)  (arm/v7)
- [ ] [Embedded Dart Sass](https://github.com/sass/dart-sass-embedded) (arm64)
- [ ] [Embedded Dart Sass](https://github.com/sass/dart-sass-embedded) (arm/v7)

The list may be longer, however this is what I'm currently watching out for.

**Comment by klakegg** [comment]
I've decided to create a [new project](https://github.com/hugoguru/dist-hugo) to provide additional ARM-based Hugo binaries. I still prefer to not compile Hugo myself, however the amd64 Docker image kills my Mac battery.

My rational for making this part happen in a separate project is to allow for transparancy and reuse outside of my intended use of creating Docker images. Additional Docker images are not yet available.

**Comment by klakegg** [comment]
Support for arm64 is added for `ext-debian` and `ext-ubuntu` as of version 0.96.0.

Node for musl on arm64 doesn't look promising, and arm/v7 is clearly not a priority out there, so I close this issue for now.

**Comment by lockejan** [comment]
Thank you for providing such images. However, it would be great to see this circumstance (no ext-alpine arm images) reflected in the readme.
