### ISSUE TITLE
Which OS to choose?

### ISSUE THREAD

**Issue by Jos512** [klakegg/docker-hugo#36]
Thanks for making and maintaining all these docker images, it looks like a lot of work.

I'm curious what the difference is between Busybox, Alpine, Debian, and Ubuntu. Which of these to choose?

I Googled of course before opening this issue, and I learned that Busybox [is the smallest](https://brianchristner.io/docker-image-base-os-size-comparison/), which sounds good. But I also learned that Alpine is [fast and secure](https://nickjanetakis.com/blog/the-3-biggest-wins-when-using-alpine-as-a-base-docker-image). But not always, because certain applications are [up to 50x slower](https://pythonspeed.com/articles/alpine-docker-python/). So perhaps Debian is better, although Ubuntu has better development behind it I learned.

I suppose that picking the right one is quite important, else you wouldn't have gone through the trouble of making 4 different ones.

But I don't really know what's best to run Hugo on. :smile: Does anyone has an insight into that?

My use case is to run the Hugo (extended version) docker with continuous deployment (CircleCI).

**Comment by klakegg** [comment]
All images are provided based on the understanding that each site developer/maintainer have different requirements and preferences, thus is it entirely up to the user to choose the image the use. All images are provided so you may switch between them at any time without having to change your site, of course based on an understand of your (changing) requirements.

All images, except those provided with `onbuild` instructions, are also suitable as base images if you are in need of extra functionality in a Docker image not provided out-of-the-box in my images.

I've not noticed any significant differences in speed when using Hugo bundled in different images, so my advice is to simple figure out which image suits you and your project today, and change another day if you feel like doing so.

Running workloads on CircleCI is no different than other use of Docker images, so all images may be used as part of your pipeline in any provider support workloads using Docker images.
