### ISSUE TITLE
Onbuild - use submodule

### ISSUE THREAD

**Issue by KoalaGeo** [klakegg/docker-hugo#37]
Hi, 

I'm trying to use klakegg/hugo:0.70.0-ext-ubuntu-onbuild but my site has the theme as a submodule

I'm getting the below which I think means the submodule hasnt installed.
   
`Error building site: "/src/content/home/publications.md:70:1": failed to extract shortcode: template for shortcode "alert" not found`

Do you know a solution?

**Comment by klakegg** [comment]
It is not clear what is the problem, and there are two possible "solutions" to this. I'll describe them here:

* If this is related to the use of *Go modules* in Hugo: In this case it is not reproducible as I'm not able to trigger any errors with the mentioned Docker image and the [DocuAPI](https://github.com/bep/docuapi) project. If this is your problem, then there is something wrong in your project.

* If this is related to the use of *Git submodules* in your project: The Docker images are created to perform the build step. In the case of code lacking in the project after running the checkout step, then the checkout step need reconfiguration. If this is your problem, then you need to fix your checkout configuration.

Please clearify which of them is your case, or bring forward more clarifications to enlighten this issue.

**Comment by KoalaGeo** [comment]
Cheers, I'll try and take another look over the next few days
