### ISSUE TITLE
BUG: unexpected --noTimes ("Error: unknown flag: --noTimes")

### ISSUE THREAD

**Issue by mliulion** [klakegg/docker-hugo#39]
There is an issue in file `src/files/alpine/bin/hugo`

Line https://github.com/klakegg/docker-hugo/blob/25b9ad65065a9ea742c0fd3e3059b16e29eb4b36/src/files/alpine/bin/hugo#L97

It brokes the  behaviour of `hugo mod` commands.

Here are some output examples:

```
$ hugo mod clean
Error: unknown flag: --noTimes
...
```

```
$ hugo mod get -u github.com/gohugoio/gohugoioTheme
go get --noTimes: package --noTimes is not in GOROOT (/usr/local/lib/go/src/--noTimes)
```
```
$ hugo mod tidy
Error: unknown flag: --noTimes
...
```

I'm running the image with this command:

```sh
docker run \
	-it \
	--rm \
	--network host \
	--user=$(id -u):$(id -g) \
	--volume $(pwd):/src \
	--entrypoint /bin/bash \
	klakegg/hugo:0.79.0-ext-alpine
```

**Comment by klakegg** [comment]
Thank you for bringing this to may attention.

I have published `klakegg/hugo:edge-ext-alpine` with the fix. The fix will be made available in all images as of next release of Hugo.

Please leave a comment if you experience further problems caused by the image when using `hugo mod`.
