### ISSUE TITLE
Add rest2html binary to images

### ISSUE THREAD

**Issue by logoff** [klakegg/docker-hugo#40]
Hi!

I love your Docker images and I used daily. But I would like to use [ReStructuredText](https://docutils.sourceforge.io/rst.html) and I can't build my Hugo site because when I try to do it your image misses `rst2html`.

May you add `rst2html` to your images?

Thank you!

**Comment by klakegg** [comment]
Hi,

Thank you for bringing this to my attention.

I've decided to make it available in the `ext` images only as I expect `rst2html` is not widely used in combination with Hugo.

I've added it for release after next Hugo release. You may test it today using the [`edge` on Docker Hub](https://hub.docker.com/repository/docker/klakegg/hugo/tags?name=edge-ext).

**Comment by logoff** [comment]
Works like a charm on `edge` images. Thank you!
