### ISSUE TITLE
Please add another syntax highlighters

### ISSUE THREAD

**Issue by aetos382** [klakegg/docker-hugo#44]
Thank you for providing such a helpful image.

Could you please consider adding pygments or rouge to this image?

I'm using Hugo and AsciiDoc to create a site.
AsciiDoctor supports the following code highlighters.

- highlightjs
- pygments
- rouge
- coderay

This image contains coderay, which doesn't support as many languages as the other highlighters. For example, coderay cannot highlight C# or PowerShell, which I would like to use.
So, I would like to use pygments or rogue.

Thank you very much.

**Comment by klakegg** [comment]
Thank you for bringing this to my attention. The inclusion of Coderay is based on my personal choice and is a reflection of my needs. I've had a look at highlightjs, which requires Asciidoctor.js, and pygments, which requires Python 2, and my conclusion at this point is to add Rouge in the release bundling Hugo 0.82.0.

I guess adding support for Asciidoctor.js may be of interest at some point, I notice a lot of stuff is happening in that space, however that must be for another issue. :smile:

I hope you find my resolution satisfying.

**Comment by aetos382** [comment]
Thank you so much!
