### ISSUE TITLE
Run Docker as non root

### ISSUE THREAD

**Issue by punksinatra** [klakegg/docker-hugo#45]
Is there a way to run the container as non-root user? I might be stupid but I tried setting up PUID and PGID but it keeps running as root and creating directory owner and group as root. 

Thanks

**Comment by jbigot** [comment]
I use:
```
docker run -p 1313:1313 "-u$(id -u):$(id -g)" --rm -it -v "$(pwd):/src" klakegg/hugo:0.82.0-ext-alpine serve
```
And get my files created as user.

**Comment by punksinatra** [comment]
> I use:
> 
> ```
> docker run -p 1313:1313 "-u$(id -u):$(id -g)" --rm -it -v "$(pwd):/src" klakegg/hugo:0.82.0-ext-alpine serve
> ```
> 
> And get my files created as user.

thanks

**Comment by jbigot** [comment]
@klakegg what would you say about updating README.md to reflect that option?

**Comment by klakegg** [comment]
@jbigot I'd say the `-u` option is standard functionality of Docker and not specific to this images.

**Comment by punksinatra** [comment]
I guess using docker compose with PUID and PGID will not work?
