### ISSUE TITLE
Add Dart Sass To The Environment

### ISSUE THREAD

**Issue by faraixyz** [klakegg/docker-hugo#46]
Dart Sass has been supported since Hugo 0.80. It would be great if it were integrated into the container.

**Comment by klakegg** [comment]
I know it is not explicitly mentioned in the readme, however the images containing Hugo extended using Debian or Ubuntu as base image already have support for `dart-sass-embedded` since the 0.81.0 release.

Did you try it out?

**Comment by faraixyz** [comment]
I haven't tried it yet. Let me do that and update the README
