### ISSUE TITLE
Typo in `onbuild` environment variables?

### ISSUE THREAD

**Issue by MoriTanosuke** [klakegg/docker-hugo#48]
I tried to use the `onbuild` tag for my personal blog today and noticed that I had to set the environment variable `HUGO_DESTINATION` instead of `HUGO_DESTINATION_ARG` to switch the output folder to my volume.

Is this a typo in the README or did I miss some other configuration for the `onbuild`? 🤔

**Comment by klakegg** [comment]
I'm unable to find a typo. Please clarify where I may find the typo.
