### ISSUE TITLE
Tag 0.91.0-asciidoctor fails to execute asciidoctor

### ISSUE THREAD

**Issue by antoniovazquezblanco** [klakegg/docker-hugo#53]
Previous versions seem to work perfectly

Output:

```Start building sites … 
hugo v0.91.0-D1DC0E9A linux/amd64 BuildDate=2021-12-17T09:50:20Z VendorInfo=gohugoio
Error: Error building site: "/src/content/footprint/F2/F2.3.adoc:1:1": access denied: "asciidoctor" is not whitelisted in policy "security.exec.allow"; the current security configuration is:

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


Total in 2276 ms```

**Comment by klakegg** [comment]
Is this specific to the Docker images, or it this specific to Hugo version 0.91.0?

**Comment by antoniovazquezblanco** [comment]
Sorry, this seems related to the security model change:

https://gohugo.io/about/security-model/#security-policy

I will have to further read on this and will come back to this issue.

**Comment by antoniovazquezblanco** [comment]
I can confirm this is hugo related and not docker image related. 

Users of the image must update their hugo config files to include the execution of asciidoctor binaries.

Thank you and sorry for the noise
