### ISSUE TITLE
Contributing towards hugo official docker images

### ISSUE THREAD

**Issue by antoniovazquezblanco** [klakegg/docker-hugo#54]
Hugo is a great candidate to be integrated in a CI/CD pipeline and this is the reason why your docker images are great to me. It seems that they are not only great to me but also to hugo people (https://gohugo.io/getting-started/installing/#docker) because they recommend yours...

I was wondering if they were open to contribution towards an official image of hugo or if you will be willing to collaborate towards one.

From users point of view, this would mean using official images instead of third party ones which seems to boost confidence on security. For developers this would mean more focused efforts towards a common goal, reducing duplicate efforts. For the hugo project this may mean key tech support that enables their product to be even be more desirable for lazy people like me!

Please, excuse me if I am stepping out of my bounds. I hope this is not taken as something bad but comes from recognizing a good quality of the work you have done.

Thanks

**Comment by klakegg** [comment]
@bep knows where to find me. :smile:

**Comment by antoniovazquezblanco** [comment]
Thank you very much! I did not know about existing issues in hugo regarding this. Thank you for your work and patience!
