### ISSUE TITLE
build as production, extended hugo required?

### ISSUE THREAD

**Issue by pvgenuchten** [klakegg/docker-hugo#55]
I'm new to the topic, but wanted to share anyway, maybe it's an error on my side.

I tried to deploy a hugo site  with onbuild-busybox with ananka theme as described in hugo quickstart

When i add `--build-arg=HUGO_ENV_ARG=production` i get a build failure indicating `extended` version is required to build scss files (probably originate from ananka theme).

Is there a build option to build the extended version, should i not use themes with scss, or something else failing here?

**Comment by klakegg** [comment]
Did you read the README?
