### ISSUE TITLE
Bump Node version

### ISSUE THREAD

**Issue by selfsimilar** [klakegg/docker-hugo#56]
The most recent LTS version of NodeJS is 16.x, but `docker-hugo` currently builds NodeJS 14.x. I'm not sure if it makes more sense to just bump to most recent LTS across the board, or make it a build option. I don't know how to do either, but I'm going to try to at least build this with latest NodeJS LTS. Happy to turn this into a pull request if successful.

**Comment by klakegg** [comment]
Thank you :smile:
