### ISSUE TITLE
Hugo 0.92.0 release

### ISSUE THREAD

**Issue by xandermann** [klakegg/docker-hugo#58]
Hi,

First, thank you for all your Docker images !

Hugo 0.92.0 has been released last week  ( https://github.com/gohugoio/hugo/tree/v0.92.0 ), and I would like to try it with docker.

I'd be happy to try and make an MR if it would help.

**Comment by xandermann** [comment]
v0.92.1 has been released : https://github.com/gohugoio/hugo/releases/tag/v0.92.1

**Comment by klakegg** [comment]
Thank you.
