### ISSUE TITLE
Signals are not sent to the hugo process

### ISSUE THREAD

**Issue by chelmi** [klakegg/docker-hugo#6]
Since the hugo process is not PID 1 in the container, signals send to the container are lost. This makes stopping the container a bit slow. See https://docs.docker.com/compose/#why-do-my-services-take-10-seconds-to-recreate-or-stop

There are a few solutions:
- Make hugo PID 1 by modifying the run.sh script to call hugo with exec
- Trap and forward signals in run.sh (see https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86)
- Use tini or another small init

More info at https://hynek.me/articles/docker-signals/

Thanks for your work!

**Comment by klakegg** [comment]
Thank you for bringing this to my attention, and I'm sorry about the late response.

I've used the first of your proposed solutions, and it seems to work as expected.

Images starting with 0.55.0 for all variants contains this fix.
