### ISSUE TITLE
missing config file 

### ISSUE THREAD

**Issue by anvesh898** [klakegg/docker-hugo#65]
docker run --rm -it \
  -v $(pwd):/src \
  -p 1313:1313 \
  klakegg/hugo:0.95.0 \
  server
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
       Run `hugo help new` for details.

**Comment by sujaykumarh** [comment]
Hello, 

By default this docker image does not include a ready made site for you to test if you are looking for it.

Here's [hugo getting started guide](https://gohugo.io/getting-started/quick-start/#step-2-create-a-new-site) to create a new site

* To run a basic hugo site you will need a `config.[yml|toml]` you can manually create it with required values or

* you can create a default hugo empty site using docker hugo by running 
  ```shell
  docker run --rm -v $(pwd):/src klakegg/hugo:TAG new site .
  ``` 
  this will create a empty hugo site in `pwd`

* run the hugo server from created site 
  ```shell
  docker run --rm -v $(pwd):/src klakegg/hugo:TAG server
  ``` 
  or run server in detached mode

<sub>*replace TAG with your required docker image tag</sub>

**resources**
* if you are new to docker check out [docker getting started](https://docs.docker.com/get-started)
* if you are looking for a basic docker compose setup checkout my [docker-compose.yml](https://github.com/sujaykumarh/notebook/blob/main/docker-compose.yml)

Hope this helps, you can close the issue if its resolved
