### ISSUE TITLE
Documentation of NodeJS version is incorrect

### ISSUE THREAD

**Issue by euantorano** [klakegg/docker-hugo#68]
[The README states](https://github.com/klakegg/docker-hugo#versions) that the NodeJS version in the `-ext` variants is `16.x`. Ina ctual fact, [the Debian version at least installs `18.x`](https://github.com/klakegg/docker-hugo/blob/master/src/docker/debian-ext/Dockerfile#L32).

**Comment by klakegg** [comment]
Thank you. It looks like I forgot to update the README this time around. :)
