### ISSUE TITLE
Update new version v0.103.0

### ISSUE THREAD

**Issue by xinro** [klakegg/docker-hugo#74]
Hi..
This docker really helped me a lot.
Hugo version v0.103.0 has been released, maybe this docker also needs to be updated.

Thank you in advance.

**Comment by floryn90** [comment]
Hi @xinro,
I cloned this repo and I'm trying to keep it updated with the latest hugo versions here: https://github.com/floryn90/docker-hugo

**Comment by wolfspyre** [comment]
is this repo not going to be updated further? why fork vs a PR?

**Comment by floryn90** [comment]
> is this repo not going to be updated further? why fork vs a PR?

I can also make the PR but if @klakegg don't have time to merge it, the result is the same.
Let's wait for an official answer from @klakegg if he will have time to maintain this repo or not
